[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "maslab-lib"
description = "MASLAB Python library for controlling hardwares"
authors = [{name = "MASLAB 2026 Staff", email = "maslab-2026-staff@mit.edu"}]
version = "0.1.7"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml",
    "adafruit-blinka",
    "numpy",
    "pyserial",
    "opencv-python",
    "flask",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
namespaces = false
